name: CI on Pull Request

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  check_ci:
    name: Check CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: latest
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Typecheck
        run: yarn tsc

      - name: ESLint
        run: yarn eslint

      - name: Prettier
        run: yarn prettier:ci
